### ISSUE TITLE
Not usable on servers for minecraft 1.19 or lower

### ISSUE THREAD

**Issue by RappyTV** [LabyMod/labymod4-server-api#4]
### General Troubleshooting

- [X] I am using the [latest version](https://github.com/LabyMod/labymod4-server-api/releases) of the LabyMod 4 Server API.
- [X] I am using the latest version of LabyMod.
- [X] I have checked for similar issues on the [Issue-tracker](https://github.com/LabyMod/labymod4-server-api/issues).
- [X] I have checked for Pull Requests that might already address this issue.

### Platforms

Spigot / Bukkit

### Affected Minecraft Version(s)

Other / Not Listed (please specify in the additional information text field at the bottom)

### Expected Behaviour

I tried to run the API on a 1.16.5 server but it didn't load the API with an error saying that it only supports minecraft >= 1.20

### Code Example for Reproduction Steps

```java
N/A
```

### Exception or Error

```yesyes
[15:58:33 ERROR]: Could not load 'plugins/labymod-server-api-bukkit-1.0.2.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Unsupported API version 1.20
        at org.bukkit.craftbukkit.v1_16_R3.util.CraftMagicNumbers.checkSupported(CraftMagicNumbers.java:361) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:149) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:414) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:322) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:393) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:269) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
        at java.lang.Thread.run(Thread.java:829) [?:?]
```

### Additional Information

The api-version in the plugin.yml needs to be adjusted to support a wider range of versions

**Comment by jumpingpxl** [comment]
thank you for the report! This has (hopefully) been fixed in https://github.com/LabyMod/labymod4-server-api/commit/6ed9e1965148feda9c0b0ee8e65052232bf7b56e
